{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hearth-home.fullname" . }}-api
  labels:
    {{- include "hearth-home.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
  annotations:
    {{- include "hearth-home.certManagerIngressAnnotation" (dict "context" . "userTls" .Values.api.ingress.tls) | nindent 4 }}
    {{- with .Values.api.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  {{- include "hearth-home.ingressTls" (dict "context" . "userTls" .Values.api.ingress.tls "hosts" .Values.api.ingress.hosts "component" "api") | nindent 2 }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "hearth-home.fullname" $ }}-api
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
