{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hearth-home.fullname" . }}-api
  labels:
    {{- include "hearth-home.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "hearth-home.selectorLabels" (dict "context" . "component" "api") | nindent 6 }}
{{- end }}
