# tests/agent-config-roundtrip.nix — NixOS VM test: agent config round-trip
#
# Verifies the agent.toml generated by modules/agent.nix round-trips
# correctly through the Rust TOML parser. Catches Nix↔Rust serialization
# mismatches without needing the full login flow infrastructure.
#
# Single-node test: boots a machine with all agent config options set,
# verifies the generated TOML contains expected fields, and confirms the
# agent starts successfully (proving it parsed the config without error).

{ pkgs, lib, hearth-agent, ... }:

let
  machineUuid = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
  machineToken = "test-machine-token-config-roundtrip";
in
pkgs.testers.nixosTest {
  name = "hearth-agent-config-roundtrip";

  nodes.machine = { config, pkgs, ... }: {
    imports = [ ../modules/agent.nix ];

    nixpkgs.overlays = [
      (final: prev: { hearth-agent = hearth-agent; })
    ];

    services.hearth.agent = {
      enable = true;
      serverUrl = "http://localhost:3000";
      machineId = machineUuid;
      pollInterval = 10;
      homeFlakeRef = "github:testorg/fleet-config";
      roleMapping = [
        { group = "engineering"; role = "developer"; }
        { group = "design"; role = "designer"; }
      ];
      defaultRole = "default";
    };

    # Pre-write machine identity so agent can start
    system.activationScripts.hearth-identity = ''
      mkdir -p /var/lib/hearth
      echo -n "${machineUuid}" > /var/lib/hearth/machine-id
      echo -n "${machineToken}" > /var/lib/hearth/machine-token
    '';

    virtualisation.memorySize = 512;
  };

  testScript = ''
    machine.start()
    machine.wait_for_unit("multi-user.target")

    # Verify the generated TOML contains the expected nested [home] section.
    # This is the exact structure the Rust parser must accept.
    config_content = machine.succeed("cat /etc/hearth/agent.toml")
    assert "[home]" in config_content, (
        f"Expected [home] section in agent.toml, got:\n{config_content}"
    )
    assert "flake_ref" in config_content, (
        f"Expected flake_ref in agent.toml, got:\n{config_content}"
    )
    assert "github:testorg/fleet-config" in config_content, (
        f"Expected flake ref value in agent.toml, got:\n{config_content}"
    )

    # Verify role_mapping round-trips correctly
    assert "engineering" in config_content, (
        f"Expected engineering group in agent.toml, got:\n{config_content}"
    )
    assert "developer" in config_content, (
        f"Expected developer role in agent.toml, got:\n{config_content}"
    )

    # Verify the agent actually started — this proves it parsed the config
    # successfully. If the TOML structure doesn't match the Rust struct,
    # the agent will fail to start with a parse error.
    machine.wait_for_unit("hearth-agent.service", timeout=30)

    # Verify agent logs don't contain config parse errors
    machine.succeed(
        "journalctl -u hearth-agent -o cat | grep -qv 'failed to.*config'"
    )

    # Verify the IPC socket is up (agent fully initialized)
    machine.wait_until_succeeds("test -S /run/hearth/agent.sock", timeout=15)
  '';
}
