{{- if and .Values.capabilities.mail .Values.stalwart.hosted }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hearth-home.fullname" . }}-stalwart-data
  labels:
    {{- include "hearth-home.componentLabels" (dict "context" . "component" "stalwart") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stalwart.persistence.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
