//! Configuration loading for the hearth-agent.
//!
//! Reads an [`AgentConfig`] from a TOML file, supporting a CLI-provided path
//! or the default `/etc/hearth/agent.toml`.

use hearth_common::config::AgentConfig;
use std::path::{Path, PathBuf};

/// Default config file location on NixOS systems.
const DEFAULT_CONFIG_PATH: &str = "/etc/hearth/agent.toml";

/// Resolve the config file path from CLI arguments.
///
/// Looks for `--config <path>` in `args`. Falls back to [`DEFAULT_CONFIG_PATH`].
pub fn resolve_config_path(args: &[String]) -> PathBuf {
    let mut iter = args.iter();
    while let Some(arg) = iter.next() {
        if arg == "--config"
            && let Some(path) = iter.next()
        {
            return PathBuf::from(path);
        }
        // Also handle --config=<path>
        if let Some(path) = arg.strip_prefix("--config=") {
            return PathBuf::from(path);
        }
    }
    PathBuf::from(DEFAULT_CONFIG_PATH)
}

/// Load and parse the agent configuration from the given TOML file.
pub fn load_config(path: &Path) -> Result<AgentConfig, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("failed to read config file {}: {e}", path.display()))?;
    let config: AgentConfig = toml::from_str(&content)
        .map_err(|e| format!("failed to parse config file {}: {e}", path.display()))?;
    Ok(config)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_path_when_no_args() {
        let args: Vec<String> = vec!["hearth-agent".into()];
        assert_eq!(
            resolve_config_path(&args),
            PathBuf::from(DEFAULT_CONFIG_PATH)
        );
    }

    #[test]
    fn path_from_flag() {
        let args: Vec<String> = vec![
            "hearth-agent".into(),
            "--config".into(),
            "/tmp/test.toml".into(),
        ];
        assert_eq!(resolve_config_path(&args), PathBuf::from("/tmp/test.toml"));
    }

    #[test]
    fn path_from_equals_form() {
        let args: Vec<String> = vec!["hearth-agent".into(), "--config=/tmp/test.toml".into()];
        assert_eq!(resolve_config_path(&args), PathBuf::from("/tmp/test.toml"));
    }

    #[test]
    fn parse_minimal_config() {
        let toml = r#"
[server]
url = "https://hearth.example.com"
"#;
        let config: AgentConfig = toml::from_str(toml).unwrap();
        assert_eq!(config.server.url, "https://hearth.example.com");
        assert_eq!(config.agent.poll_interval_secs, 60);
        assert_eq!(config.agent.socket_path, "/run/hearth/agent.sock");
    }

    #[test]
    fn parse_config_with_home_flake_ref() {
        // This TOML matches the exact format generated by modules/agent.nix
        // when homeFlakeRef is set. If this test breaks, the Nix module and
        // Rust struct have diverged.
        let toml = r#"
[server]
url = "https://hearth.example.com"

[home]
flake_ref = "github:myorg/fleet-config"
"#;
        let config: AgentConfig = toml::from_str(toml).unwrap();
        let home = config.home.expect("home config should be present");
        assert_eq!(home.flake_ref, "github:myorg/fleet-config");
    }

    #[test]
    fn parse_config_with_empty_cache_section() {
        // agent.nix generates an empty [cache] section when binaryCacheUrl is null.
        // This must not crash the parser.
        let toml = r#"
[server]
url = "https://hearth.example.com"

[cache]
"#;
        let config: AgentConfig = toml::from_str(toml).unwrap();
        let cache = config.cache.expect("cache section should be present");
        assert!(cache.url.is_none());
    }

    #[test]
    fn parse_config_without_home_is_none() {
        let toml = r#"
[server]
url = "https://hearth.example.com"
"#;
        let config: AgentConfig = toml::from_str(toml).unwrap();
        assert!(config.home.is_none());
    }

    #[test]
    fn parse_full_nixos_generated_config() {
        // Mirrors the complete TOML that agent.nix generates with all options set.
        // Catches any field that Nix emits but Rust silently ignores.
        let toml = r#"
[server]
url = "https://hearth.example.com"
machine_id = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"

[agent]
poll_interval_secs = 30
socket_path = "/run/hearth/agent.sock"
machine_token_path = "/var/lib/hearth/machine-token"

[home]
flake_ref = "github:myorg/fleet-config"

[cache]
url = "https://cache.hearth.example.com/fleet-prod"

[role_mapping]
default_role = "default"

[[role_mapping.mappings]]
group = "engineering"
role = "developer"

[[role_mapping.mappings]]
group = "design"
role = "designer"

[headscale]
report_ip = true
mesh_server_url = "http://100.64.0.1:3000"
"#;
        let config: AgentConfig = toml::from_str(toml).unwrap();
        assert_eq!(config.server.url, "https://hearth.example.com");
        assert_eq!(config.home.unwrap().flake_ref, "github:myorg/fleet-config");
        assert_eq!(
            config.cache.unwrap().url.unwrap(),
            "https://cache.hearth.example.com/fleet-prod"
        );
        let rm = config.role_mapping.unwrap();
        assert_eq!(rm.mappings.len(), 2);
        assert_eq!(rm.mappings[0].role, "developer");
        let hs = config.headscale.unwrap();
        assert!(hs.report_ip);
        assert_eq!(hs.mesh_server_url.unwrap(), "http://100.64.0.1:3000");
    }
}
